#!/usr/bin/env bash
# ============================================================================
# Opencode Owl Install Proxy — Bootstrap Script
# Version: 1.0.0
# ============================================================================
#
# This script automates the installation and configuration of the OpenCode
# billing proxy. It detects the OS, downloads the appropriate binary,
# configures environment variables, and validates connectivity.
#
# Usage:
#   chmod +x install.sh
#   ./install.sh --proxy-url https://proxy.example.com --token your-token
#
# Environment Variables:
#   OPENCODE_PROXY_URL   — The base URL of the billing proxy
#   OPENCODE_PROXY_TOKEN — Authentication token for the proxy
#   OPENCODE_PROXY_MODE  — "strict" (fail-closed) or "lenient" (fail-open, default)
#
# ============================================================================

set -euo pipefail

VERSION="1.0.0"
PROXY_URL="${OPENCODE_PROXY_URL:-}"
PROXY_TOKEN="${OPENCODE_PROXY_TOKEN:-}"
PROXY_MODE="${OPENCODE_PROXY_MODE:-lenient}"
INSTALL_DIR="${HOME}/.local/bin"
CONFIG_DIR="${HOME}/.config/opencode-proxy"
PROXY_BIN_NAME="opencode-proxy"
VERBOSE=0

# ---- Color Helpers ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[OWL-INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[OWL-WARN]${NC} $*"; }
error() { echo -e "${RED}[OWL-ERR]${NC} $*"; }
ok()    { echo -e "${GREEN}[OWL-OK]${NC} $*"; }

# ---- Argument Parsing ----
while [[ $# -gt 0 ]]; do
  case "$1" in
    --proxy-url)   PROXY_URL="$2"; shift 2 ;;
    --token)       PROXY_TOKEN="$2"; shift 2 ;;
    --mode)        PROXY_MODE="$2"; shift 2 ;;
    --install-dir) INSTALL_DIR="$2"; shift 2 ;;
    --verbose)     VERBOSE=1; shift ;;
    --help|-h)
      echo "Usage: $0 [options]"
      echo "  --proxy-url URL     Billing proxy base URL (or set OPENCODE_PROXY_URL)"
      echo "  --token TOKEN       Authentication token (or set OPENCODE_PROXY_TOKEN)"
      echo "  --mode MODE         'strict' or 'lenient' (default: lenient)"
      echo "  --install-dir DIR   Binary install directory (default: ~/.local/bin)"
      echo "  --verbose           Enable verbose output"
      echo "  --help              Show this help message"
      exit 0
      ;;
    *) error "Unknown option: $1"; exit 1 ;;
  esac
done

# ---- Pre-flight Checks ----
info "Opencode Owl Install Proxy v${VERSION}"
info "Running pre-flight checks..."

if [[ -z "${PROXY_URL}" ]]; then
  error "No proxy URL provided. Use --proxy-url or set OPENCODE_PROXY_URL."
  exit 1
fi

if [[ -z "${PROXY_TOKEN}" ]]; then
  error "No proxy token provided. Use --token or set OPENCODE_PROXY_TOKEN."
  exit 1
fi

if ! command -v curl &>/dev/null && ! command -v wget &>/dev/null; then
  error "Neither curl nor wget found. Please install one."
  exit 1
fi

# ---- OS Detection ----
detect_os() {
  local os_name="unknown"
  local os_arch="unknown"

  case "$(uname -s)" in
    Linux*)   os_name="linux" ;;
    Darwin*)  os_name="darwin" ;;
    MINGW*|MSYS*|CYGWIN*) os_name="windows" ;;
    *)        os_name="$(uname -s | tr '[:upper:]' '[:lower:]')" ;;
  esac

  case "$(uname -m)" in
    x86_64|amd64) os_arch="amd64" ;;
    aarch64|arm64) os_arch="arm64" ;;
    *)            os_arch="$(uname -m)" ;;
  esac

  echo "${os_name}-${os_arch}"
}

PLATFORM="$(detect_os)"
info "Detected platform: ${PLATFORM}"

# ---- Download Proxy Binary ----
download_binary() {
  local download_url="${PROXY_URL}/releases/owl-proxy/${VERSION}/${PLATFORM}/owl-proxy"
  local target="${INSTALL_DIR}/${PROXY_BIN_NAME}"

  mkdir -p "${INSTALL_DIR}"

  info "Downloading owl-proxy binary from ${download_url}..."

  if command -v curl &>/dev/null; then
    curl -fsSL -o "${target}" "${download_url}"
  else
    wget -q -O "${target}" "${download_url}"
  fi

  chmod +x "${target}"
  ok "Binary installed to ${target}"
}

# Skip download if binary already exists and version matches
if [[ -x "${INSTALL_DIR}/${PROXY_BIN_NAME}" ]]; then
  installed_version="$("${INSTALL_DIR}/${PROXY_BIN_NAME}" --version 2>/dev/null || echo 'unknown')"
  if [[ "${installed_version}" == "${VERSION}" ]]; then
    info "owl-proxy v${VERSION} already installed. Skipping download."
  else
    warn "Installed version (${installed_version}) differs from target (${VERSION}). Re-downloading..."
    download_binary
  fi
else
  download_binary
fi

# ---- Write Configuration ----
mkdir -p "${CONFIG_DIR}"

cat > "${CONFIG_DIR}/config.env" <<EOF
# Opencode Owl Proxy Configuration
# Auto-generated by owl-install v${VERSION}
# Do not edit manually — use: owl-proxy config set <key> <value>

OPENCODE_PROXY_URL=${PROXY_URL}
OPENCODE_PROXY_TOKEN=${PROXY_TOKEN}
OPENCODE_PROXY_MODE=${PROXY_MODE}
EOF

chmod 600 "${CONFIG_DIR}/config.env"
ok "Configuration written to ${CONFIG_DIR}/config.env"

# ---- Shell Profile Integration ----
inject_shell_profile() {
  local profile_file=""
  local shell_name="$(basename "${SHELL:-bash}")"

  case "${shell_name}" in
    zsh)  profile_file="${HOME}/.zshrc" ;;
    bash) profile_file="${HOME}/.bashrc" ;;
    fish) profile_file="${HOME}/.config/fish/config.fish" ;;
    *)    profile_file="${HOME}/.profile" ;;
  esac

  local marker="# >>> opencode-owl-proxy >>>"
  local marker_end="# <<< opencode-owl-proxy <<<"

  # Remove any existing owl-proxy block
  if grep -q "${marker}" "${profile_file}" 2>/dev/null; then
    sed -i.bak "/${marker}/,/${marker_end}/d" "${profile_file}"
  fi

  # Append new block
  {
    echo ""
    echo "${marker}"
    echo "export OPENCODE_PROXY_URL=\"${PROXY_URL}\""
    echo "export OPENCODE_PROXY_TOKEN=\"${PROXY_TOKEN}\""
    echo "export OPENCODE_PROXY_MODE=\"${PROXY_MODE}\""
    echo "export PATH=\"\${PATH}:${INSTALL_DIR}\""
    echo "${marker_end}"
  } >> "${profile_file}"

  ok "Shell profile (${profile_file}) updated with proxy environment variables"
}

inject_shell_profile

# ---- Connectivity Validation ----
info "Validating proxy connectivity..."

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
  -H "Authorization: Bearer ${PROXY_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"model":"test","messages":[{"role":"user","content":"ping"}],"max_tokens":1}' \
  "${PROXY_URL}/v1/chat/completions" 2>/dev/null || echo "000")

case "${HTTP_CODE}" in
  200|201)
    ok "Proxy connectivity validated (HTTP ${HTTP_CODE})"
    ;;
  401|403)
    error "Authentication failed (HTTP ${HTTP_CODE}). Check your proxy token."
    exit 1
    ;;
  429)
    warn "Rate-limited by proxy (HTTP 429). Proxy is reachable but quota may be exhausted."
    ;;
  000)
    error "Cannot reach proxy at ${PROXY_URL}. Check URL and network connectivity."
    if [[ "${PROXY_MODE}" == "lenient" ]]; then
      warn "Proxy mode is 'lenient' — OpenCode will fall back to direct API calls."
    else
      error "Proxy mode is 'strict' — all OpenCode calls will fail until proxy is reachable."
      exit 1
    fi
    ;;
  *)
    warn "Unexpected response (HTTP ${HTTP_CODE}). Proxy may be partially available."
    ;;
esac

# ---- Summary ----
echo ""
echo "============================================"
ok "Opencode Owl Install Proxy — Setup Complete"
echo "============================================"
echo ""
echo "  Proxy URL:     ${PROXY_URL}"
echo "  Proxy Mode:    ${PROXY_MODE}"
echo "  Binary:        ${INSTALL_DIR}/${PROXY_BIN_NAME}"
echo "  Config:        ${CONFIG_DIR}/config.env"
echo "  Shell Profile: Updated (restart shell or source it)"
echo ""
echo "  Next steps:"
echo "    1. Run: source ~/.bashrc  (or ~/.zshrc)"
echo "    2. Verify: opencode-proxy --version"
echo "    3. Test:   opencode-proxy test-connection"
echo ""

exit 0
